// Data
const levels = [
  {
    actionKeys: ["right arrow"],
    action: "move to the second character",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: [],
    minKeystrokes: 1,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [1, 1],
  },
  {
    actionKeys: ["right arrow", "right arrow"],
    action: "move to the third character",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: [],
    minKeystrokes: 2,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [2, 2],
  },
  {
    actionKeys: ["right arrow", "right arrow", "right arrow"],
    action: "move to the third character",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: [],
    minKeystrokes: 3,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [3, 3],
  },
  {
    actionKeys: ["right arrow", "right arrow", "right arrow", "right arrow"],
    action: "move to the fourth character",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: [],
    minKeystrokes: 4,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [4, 4],
  },
  {
    actionKeys: [
      "right arrow",
      "right arrow",
      "right arrow",
      "right arrow",
      "right arrow",
    ],
    action: "move to the fifth character",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: [],
    minKeystrokes: 5,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [5, 5],
  },
  {
    actionKeys: ["right arrow"],
    action: "move to the end of the first word",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["alt"],
    minKeystrokes: 2,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [5, 5],
  },
  {
    actionKeys: ["right arrow", "right arrow"],
    action: "move to the end of the second word",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["alt"],
    minKeystrokes: 3,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [11, 11],
  },
  {
    actionKeys: ["right arrow", "right arrow", "right arrow"],
    action: "move to the end of the third word",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["alt"],
    minKeystrokes: 4,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [17, 17],
  },
  {
    actionKeys: ["right arrow", "right arrow", "right arrow", "right arrow"],
    action: "move to the end of the fourth word",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["alt"],
    minKeystrokes: 5,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [21, 21],
  },
  {
    // If more than five, add ellipsis
    actionKeys: [
      "right arrow",
      "right arrow",
      "right arrow",
      "right arrow",
      "right arrow",
    ],
    action: "move to the end of the line",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["alt"],
    minKeystrokes: 9,
    startingCursorPosition: [0, 0],
    finalCursorLocation: [55, 55],
  },
  {
    actionKeys: ["right arrow"],
    action: "skip to the end of the line",
    cursorPlacement: "the beginning",
    keyword: "Right",
    activeKeys: ["meta"],
    minKeystrokes: 2,
    finalCursorLocation: [56, 56],
  },
  {
    actionKeys: ["left arrow"],
    action: "skip to the beginning of the line",
    cursorPlacement: "the middle",
    keyword: "Left",
    activeKeys: ["meta"],
    minKeystrokes: 2,
    startingCursorPosition: [12, 12],
  },
  {
    actionKeys: ["up arrow"],
    action: "skip to the beginning of the text",
    cursorPlacement: "the end",
    keyword: "Up",
    activeKeys: ["meta"],
    minKeystrokes: 2,
    startingCursorPosition: [141, 141],
    finalCursorLocation: [0, 0],
  },
  {
    actionKeys: ["down arrow"],
    action: "skip to the end of the text",
    cursorPlacement: "the beginning",
    keyword: "Down",
    activeKeys: ["meta"],
    minKeystrokes: 2,
    finalCursorLocation: [141, 141],
  },
  {
    actionKeys: ["right arrow"],
    action: "highlight the first word",
    cursorPlacement: "the beginning of the text",
    keyword: "Right",
    activeKeys: ["alt", "shift"],
    minKeystrokes: 3,
    finalCursorLocation: [0, 5],
  },
  {
    actionKeys: ["left arrow"],
    action: "highlight the first word",
    cursorPlacement: "after the first word",
    keyword: "Left",
    activeKeys: ["alt", "shift"],
    minKeystrokes: 3,
    startingCursorPosition: [5, 5],
    finalCursorLocation: [0, 5],
  },
  {
    actionKeys: ["down arrow"],
    action: "highlight the first line",
    cursorPlacement: "the beginning of the text",
    keyword: "Down",
    activeKeys: ["alt", "shift"],
    minKeystrokes: 3,
    finalCursorLocation: [0, 57],
  },
  {
    actionKeys: ["up arrow"],
    action: "highlight the first line",
    cursorPlacement: "at the end of the first line",
    keyword: "Up",
    activeKeys: ["alt", "shift"],
    minKeystrokes: 3,
    startingCursorPosition: [56, 56],
    finalCursorLocation: [0, 56],
  },
  {
    actionKeys: ["delete"],
    action: "delete the first word",
    cursorPlacement: "after the first word",
    keyword: "Backspace",
    activeKeys: ["alt"],
    minKeystrokes: 2,
    startingCursorPosition: [5, 5],
    finalCursorLocation: [0, 0],
  },
  {
    actionKeys: ["delete"],
    action: "delete the first line",
    cursorPlacement: "at the end of the first line",
    keyword: "Backspace",
    activeKeys: ["meta"],
    minKeystrokes: 2,
    startingCursorPosition: [56, 56],
    finalCursorLocation: [0, 0],
  },
  {
    actionKeys: ["K"],
    action: "delete the last word of the first line",
    cursorPlacement: "before the last word of the first line",
    keyword: "K",
    activeKeys: ["control"],
    minKeystrokes: 2,
    startingCursorPosition: [50, 50],
    finalCursorLocation: [50, 50],
  },
];

window.levels = levels;
