export type GameLevel = {
  actionKeys: string[];
  action?: string;
  cursorPlacement: string;
  newCursorPlacement?: string;
  newKey?: string;
  keyword: string;
  activeKeys: string[];
  minKeystrokes: number;
  startingCursorPosition?: number[];
  finalCursorLocation?: number[];
};

// Data
export const tracks = [
  [
    {
      actionKeys: ["ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "after the first character",
      newKey: "ArrowRight",
      keyword: "Right",
      activeKeys: [] as string[],
      minKeystrokes: 1,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [1, 1],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "after the second character",
      keyword: "Right",
      activeKeys: [],
      minKeystrokes: 2,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [2, 2],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "after the third character",
      keyword: "Right",
      activeKeys: [],
      minKeystrokes: 3,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [3, 3],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight", "ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "to after the fourth character",
      keyword: "Right",
      activeKeys: [],
      minKeystrokes: 4,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [4, 4],
    },
    {
      actionKeys: [
        "ArrowRight",
        "ArrowRight",
        "ArrowRight",
        "ArrowRight",
        "ArrowRight",
      ],
      cursorPlacement: "the beginning",
      newCursorPlacement: "after the fifth character",
      keyword: "Right",
      activeKeys: [],
      minKeystrokes: 5,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [5, 5],
    },
    {
      actionKeys: ["ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the first word",
      newKey: "AltLeft",
      keyword: "Right",
      activeKeys: ["alt"],
      minKeystrokes: 2,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [5, 5],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the second word",
      keyword: "Right",
      activeKeys: ["alt"],
      minKeystrokes: 3,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [11, 11],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the third word",
      keyword: "Right",
      activeKeys: ["alt"],
      minKeystrokes: 4,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [17, 17],
    },
    {
      actionKeys: ["ArrowRight", "ArrowRight", "ArrowRight", "ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the fourth word",
      keyword: "Right",
      activeKeys: ["alt"],
      minKeystrokes: 5,
      startingCursorPosition: [0, 0],
      finalCursorLocation: [21, 21],
    },
    {
      actionKeys: ["ArrowRight"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the line",
      newKey: "MetaLeft",
      keyword: "Right",
      activeKeys: ["meta"],
      minKeystrokes: 2,
      finalCursorLocation: [56, 56],
    },
    {
      actionKeys: ["ArrowLeft"],
      cursorPlacement: "the middle",
      newCursorPlacement: "the beginning of the line",
      keyword: "Left",
      activeKeys: ["meta"],
      minKeystrokes: 2,
      startingCursorPosition: [12, 12],
    },
    {
      actionKeys: ["ArrowUp"],
      cursorPlacement: "the end",
      newCursorPlacement: "the beginning of the text",
      keyword: "Up",
      activeKeys: ["meta"],
      minKeystrokes: 2,
      startingCursorPosition: [141, 141],
      finalCursorLocation: [0, 0],
    },
    {
      actionKeys: ["ArrowDown"],
      cursorPlacement: "the beginning",
      newCursorPlacement: "the end of the text",
      keyword: "Down",
      activeKeys: ["meta"],
      minKeystrokes: 2,
      finalCursorLocation: [141, 141],
    },
  ],
  [
    {
      actionKeys: ["ArrowRight"],
      action: "highlight the first word",
      cursorPlacement: "the beginning of the text",
      newKey: "ShiftLeft",
      keyword: "Right",
      activeKeys: ["alt", "shift"],
      minKeystrokes: 3,
      finalCursorLocation: [0, 5],
    },
    {
      actionKeys: ["ArrowLeft"],
      action: "highlight the first word",
      cursorPlacement: "after the first word",
      keyword: "Left",
      activeKeys: ["alt", "shift"],
      minKeystrokes: 3,
      startingCursorPosition: [5, 5],
      finalCursorLocation: [0, 5],
    },
    {
      actionKeys: ["ArrowDown"],
      action: "highlight the first line",
      cursorPlacement: "the beginning of the text",
      keyword: "Down",
      activeKeys: ["shift"],
      minKeystrokes: 3,
      finalCursorLocation: [0, 57],
    },
    {
      actionKeys: ["ArrowUp"],
      action: "highlight the first line",
      cursorPlacement: "at the end of the first line",
      keyword: "Up",
      activeKeys: ["shift"],
      minKeystrokes: 3,
      startingCursorPosition: [56, 56],
      finalCursorLocation: [0, 56],
    },
  ],
  [
    {
      actionKeys: ["Backspace"],
      action: "delete the first word",
      cursorPlacement: "after the first word",
      newKey: "Backspace",
      keyword: "Backspace",
      activeKeys: ["alt"],
      minKeystrokes: 2,
      startingCursorPosition: [5, 5],
      finalCursorLocation: [0, 0],
    },
    {
      actionKeys: ["Backspace"],
      action: "delete the first line",
      cursorPlacement: "at the end of the first line",
      keyword: "Backspace",
      activeKeys: ["meta"],
      minKeystrokes: 2,
      startingCursorPosition: [56, 56],
      finalCursorLocation: [0, 0],
    },
    {
      actionKeys: ["K"],
      action: "delete the last word of the first line",
      cursorPlacement: "before the last word of the first line",
      newKey: "ControlLeft",
      keyword: "K",
      activeKeys: ["control"],
      minKeystrokes: 2,
      startingCursorPosition: [50, 50],
      finalCursorLocation: [50, 50],
    },
  ],
];

export {};
